name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # necessary for writing artifacts
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # necessary for generating changelogs

      # Setup Go
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      # リリース
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
